### ISSUE TITLE
feature request: pretrained model

### ISSUE THREAD

**Issue by mansur007** [Galaxies99/DeepHDR-pytorch#10]
Hello,

Would you be able to include a pretrained model in this repo?
It will help the community a lot.

Thank you

**Comment by Galaxies99** [comment]
Hi,

The model was trained some years ago, and I'm sorry that I cannot find the checkpoints now. As far as I can recall, the model is not difficult to train, so I believe that running the training code for several hours can achieve the similar results illustrated in the README. 

If you want the exact model that achieves the same results in the paper, I would suggest asking the original authors for help.

**Comment by mansur007** [comment]
I see, do you remember how many epochs it needed roughly? Thank you

**Comment by Galaxies99** [comment]
I think I trained for the entire 50 epochs as stated in the configuration file (utils/config.py). The best results might appear during the middle of the training (maybe about 30~40 epochs).
