### ISSUE TITLE
HDRpatches.py

### ISSUE THREAD

**Issue by Qirui-Y** [Galaxies99/DeepHDR-pytorch#6]
Thank you very much for your code. When you use HDRpatches.py for training, do you have the problem of image size misalignment?

**Comment by Galaxies99** [comment]
Hello!

I haven't encounter that problem so far. Can you describe it in details?

**Comment by Qirui-Y** [comment]
thank you for your reply. I am not sure if it is caused by the boundary patch. The reason why using HDR.py is slow is that there are some unnecessary steps in the data preprocessing.
