### ISSUE TITLE
LDR2HDR

### ISSUE THREAD

**Issue by Qirui-Y** [Galaxies99/DeepHDR-pytorch#7]
Regarding LDR2HDR inHDRutils.py, why do we need to multiply 2 and then subtract 1?

**Comment by Galaxies99** [comment]
Sorry for the late response.

My understanding is that it can normalize/standardlize the value range of pixels in the image. For the data preprocessing part, I mainly follow the implementation of the origin DeepHDR repository (See https://github.com/elliottwu/DeepHDR/ for details).

**Comment by Qirui-Y** [comment]
邮件可能无法及时回复，如有查收会尽快回复您。
