### ISSUE TITLE
dataset download link is broken

### ISSUE THREAD

**Issue by mansur007** [Galaxies99/DeepHDR-pytorch#9]
Hello!  
Thank you very much for this repo!

It seems that the dataset download link (https://www.robots.ox.ac.uk/~szwu/storage/hdr/kalantari_dataset.zip) is broken at the moment.  
I tried to use the datasets from https://cseweb.ucsd.edu//~viscomp/projects/SIG17HDR/ but they have different structure.
For example, Training/001 has three .tif files, exposure.txt, and HDRImg.hdr.  
So I am not sure what I should pass as inputs to KlantariDataset() from dataset/HDRpatches.py  
I am especially unsure what values should  *ref_name*, *input_exp_name*, and  *ref_exp_name* take.

Any help will be highly appreciated. Thank you

**Comment by mansur007** [comment]
I used this link https://www.robots.ox.ac.uk/~szwu/storage/18_hdr/kalantari_dataset.zip from the original repository and it worked.  
I guess the link in *data/get_data.sh* should be updated  
Thanks

**Comment by Galaxies99** [comment]
Hi,

The link has been fixed, it seems that the original author changed the link and I did not notice that. Thank you for reporting this issue as well as the solution!
